repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.0.1
    hooks:
      - id: check-case-conflict
      - id: check-ast
      - id: check-builtin-literals
      - id: check-byte-order-marker
      - id: check-toml
      - id: check-yaml
      - id: check-json
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: debug-statements
      - id: trailing-whitespace
      - id: debug-statements
      - id: mixed-line-ending
        args: [--fix=lf]

      # check for file bigger than 500kb
      - id: end-of-file-fixer
      - id: double-quote-string-fixer
      - id: fix-encoding-pragma
        args: [--remove]

  - repo: https://github.com/timothycrosley/isort
    rev: 4.3.21
    hooks:
      - id: isort

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.4.3
    hooks:
      - id: pyupgrade
        args: ["--py36-plus"]

  - repo: https://github.com/Trim21/mirrors-autoflake
    rev: v1.3.1
    hooks:
      - id: autoflake
        require_serial: true
        args:
          [
            "--in-place",
            "--remove-unused-variables",
            "--remove-all-unused-imports",
            "--expand-star-imports",
          ]

  - repo: https://github.com/PyCQA/doc8.git
    rev: 0.8.1rc3
    hooks:
      - id: doc8
        name: Check rst file
        args: ["--config", "setup.cfg"]
        files: \.rst$

  - repo: https://github.com/Trim21/poetry-check-lock.git
    rev: v0.0.3
    hooks:
      - id: poetry-check-lock

  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [python]
        args: ["--config=setup.cfg"]

      - id: mypy
        name: mypy
        entry: mypy
        language: system
        types: [python]
        files: 'transmission_rpc.*$'

      - id: yapf
        name: yapf
        entry: yapf -i
        require_serial: true
        language: system
        types: [python]
